published:
  - app:
      category: life
      application: weather
      name: 天气
      publisher_data: 2018-10-01
      url: /service/weather
      desc: this is a weather app.
  - app:
      category: life
      application: Image backup
      name: 图片备份
      publisher_data: 2018-10-01
      url: /service/image
      desc: this is a Image backup app.
  - app:
      category: life
      application: stock
      name: 股票
      publisher_data: 2018-10-01
      url: /service/stock
      desc: this is a stock app.
  - app:
      category: life
      application: constellation
      name: 星座运势
      publisher_data: 2018-10-01
      url: /service/constellation
      desc: this is a constellation app.
  - app:
      category: life
      application: joke
      name: 笑话
      publisher_data: 2018-10-01
      url: /service/constellation
      desc: this is a jock app.

developing:
  app:
      category: test
