# Generated by Django 2.0.5 on 2019-05-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_focus_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='focus_app',
            new_name='menu',
        ),
    ]
